// File generated by FlutterFire CLI.
 import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqGudJuBUGiscYkYEWfiEW6a2HqqPRjcg',
    appId: '1:979891966794:web:6467b36d80f8c1d81ae7b3',
    messagingSenderId: '979891966794',
    projectId: 'shazamovie',
    authDomain: 'shazamovie.firebaseapp.com',
    storageBucket: 'shazamovie.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY4adM7PFDccin9R2j7LOSSEcMpMHpBds',
    appId: '1:979891966794:android:8b1580d22502f4571ae7b3',
    messagingSenderId: '979891966794',
    projectId: 'shazamovie',
    storageBucket: 'shazamovie.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChFsnAXd3gdObPfrUOTz56YD3ih5Ps7lE',
    appId: '1:979891966794:ios:6316b8ec6b9686ec1ae7b3',
    messagingSenderId: '979891966794',
    projectId: 'shazamovie',
    storageBucket: 'shazamovie.appspot.com',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChFsnAXd3gdObPfrUOTz56YD3ih5Ps7lE',
    appId: '1:979891966794:ios:b41d40becd9b857c1ae7b3',
    messagingSenderId: '979891966794',
    projectId: 'shazamovie',
    storageBucket: 'shazamovie.appspot.com',
    iosBundleId: 'com.example.moviesApp.RunnerTests',
  );
}
